export const data = {
  data: {
    header: {
      workOrderType: 'Acceptance Test',
      customer: '',
      customerAddress: '',
      owner: '',
      ownerAddress: '',
      date: '',
      workOrder: '',
      temperature: '',
      humidity: '',
      identification: 'Identification',
      parent: 'Location',
      assetId: '',
      building: 'Building',
      floor: '',
      room: '',
      section: 'Section',
    },
    nameplateInformation: { manufacturer: 'Manufacturer', serialNumber: 'Serial Number', kVRating: 'kV Rating', ampereRating: 'Ampere Rating' },
    pleaseSelectTests: { visualInspection: true, insulationResistance: true, leakageCurrent: true },
    visualInspection: {
      mechanicalDamage: 'Mechanical Damage',
      paintCondition: 'Paint Condition',
      cleanliness: 'Cleanliness',
      properlyGrounded: 'Properly Grounded',
      systemConfiguration: 'System Configuration',
      electricalDamage: 'Electrical Damage',
      coversAndDoors: 'Covers and Doors',
      electricalConnections: 'Electrical Connections',
      systemVoltage: 'System Voltage',
    },
    insulationResistance: {
      testVoltage: { ac: true, dc: false },
      phaseAResistance1: '4',
      phaseBResistance1: '5',
      phaseCResistance1: '6',
      phaseAResistance2: '7',
      phaseBResistance2: '8',
      phaseCResistance2: '9',
      phaseAResistance3: '10',
      phaseBResistance3: '11',
      phaseCResistance3: '12',
      phaseAResistance4: '13',
      phaseBResistance4: '14',
      phaseCResistance4: '15',
      phaseATestVoltage: 1,
      phaseBTestVoltage: 2,
      phaseCTestVoltage: 3,
    },
    leakageCurrent: { testVoltage: { ac: true, dc: false }, phaseALeakage: '19', phaseBLeakage: '20', phaseCLeakage: '21', phaseATestVoltage: 16, phaseBTestVoltage: 17, phaseCTestVoltage: 18 },
    footer: { selection1: '', inspectionVerdict: 'Pass', comments: 'The medium-voltage bus PASSED and is acceptable for operation.', defects: 'no', violations: 'no', testEquipmentNumber: '', testedBy: 'Test', testEquipmentCalibrationTable: [{ equipmentId: '22', name: '23', serialNumber: '24', calibrationDate: '2023-06-08T00:00:00+05:30' }] },
  },
}
